export const LOGIN_STATUS = 'LOGIN_STATUS'
export const LOGOUT_STATUS = 'LOGOUT_STATUS'

export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_LOADING = 'ORDER_LOADING'
export const ORDER_ERROR = 'ORDER_ERROR'

export const ORDER_ID_SUCCESS = 'ORDER_ID_SUCCESS'
export const ORDER_ID_LOADING = 'ORDER_ID_LOADING'
export const ORDER_ID_ERROR = 'ORDER_ERROR'
